services:
  - type: web
    name: task-app
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm install --include=dev --prefix ../client && npm run build --prefix ../client
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://merntask:9phrbVoQtbtcqAaD@cluster0.xhouvqy.mongodb.net/MERNTASK?retryWrites=true&w=majority
      - key: CLIENT_ORIGIN
        value: https://task-09pd.onrender.com
